"""
Django settings for sisevadoc project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

import os
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lfh&1sr*=t^x(s7+83(fhvj=vh4u*!t8z78gb(3!ppq3ab5#oh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.usuarios',
    'apps.academico',
    'apps.evaluacion',
    'apps.procesoeval',
    'apps.plmejoras',
    'apps.santiguo',
    'apps.sdcarrera',
    'bootstrap3',
    'smart_selects',
    'constance',
    'constance.backends.database',
    'auditlog',
    'qr_code',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    #midelware de autologout
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'sisevadoc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR,"plantillas")),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sisevadoc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #}
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sisevadoca',                      
        'USER': 'postgres',
        'PASSWORD': '123456789',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es-la'

TIME_ZONE = 'Etc/GMT+4'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
#medios
MEDIA_URL="/media/"
MEDIA_ROOT=os.path.join(BASE_DIR,"media")
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS=(os.path.join(BASE_DIR,"staticfiles"),)

#login
LOGIN_REDIRECT_URL = reverse_lazy('usuarios:main')
LOGIN_URL = reverse_lazy('usuarios:login')
LOGOUT_URL = reverse_lazy('usuarios:logout')
LOGOUT_REDIRECT_URL = reverse_lazy('usuarios:login')

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'reynaldo.pereira.heredia@gmail.com'
EMAIL_HOST_PASSWORD = 'nosdurno1988'
EMAIL_PORT = 587

PASSWORD_RESET_TIMEOUT_DAYS = 1

#USE_DJANGO_JQUERY = True
#JQUERY_URL = True

#configuracion dinamica 
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_CONFIG = {
    'GESTION_ACTIVO': (False, 'Determina eleccion manual de gestion',bool),
    'GESTION': (2018, 'Valor de la gestion manual',int),
    'PERIODO': (1, 'Valor de la gestion manual',int),
    'PLN_MEJORA': (False, 'Activar y desactivar plan de mejoras',bool),
    'GESTION_PLNM': (2018, 'Valor de la gestion de activacion del plan de mejoras',int),
    'PERIODO_PLNM': (1, 'Valor del periodo de activacion del plan de mejoras',int),
    'CREAR_USER':(False,'Indica si se puede crear usuario docente',bool),
}
CONSTANCE_SUPERUSER_ONLY = False

#autologout
SESSION_EXPIRE_SECONDS = 3600 * 4 #media hoara
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True