# Generated by Django 2.0.8 on 2019-03-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docentea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidop', models.CharField(max_length=100)),
                ('apellidom', models.CharField(max_length=100)),
                ('ci', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='evaluaciona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('materia', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=7)),
                ('auto_eval_docente', models.FloatField()),
                ('inf_dir', models.FloatField()),
                ('opi_est', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='eval_dir',
            fields=[
                ('evaluaciona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='santiguo.evaluaciona')),
                ('pregunta_1', models.FloatField(verbose_name='¿El docente cumple con el horario de clases establecido?')),
                ('pregunta_2', models.FloatField(verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?')),
                ('pregunta_3', models.FloatField(verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?')),
                ('pregunta_4', models.FloatField(verbose_name='¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?')),
                ('pregunta_5', models.FloatField(verbose_name='¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política.?')),
                ('pregunta_6', models.FloatField(verbose_name='¿El docente motiva a los alumnos para la participación activa del mismo en clases?')),
                ('pregunta_7', models.FloatField(verbose_name='¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?')),
                ('pregunta_8', models.FloatField(verbose_name='¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?')),
                ('pregunta_9', models.FloatField(verbose_name='¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?')),
                ('pregunta_10', models.FloatField(verbose_name='¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?')),
                ('pregunta_11', models.FloatField(verbose_name='¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?')),
                ('pregunta_12', models.FloatField(verbose_name='¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?')),
                ('pregunta_13', models.FloatField(verbose_name='¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?')),
                ('pregunta_14', models.FloatField(verbose_name='¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?')),
                ('pregunta_15', models.FloatField(verbose_name='¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?')),
                ('pregunta_16', models.FloatField(verbose_name='¿El docente domina los temas de la asignatura?')),
                ('pregunta_17', models.FloatField(verbose_name='¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?')),
                ('pregunta_18', models.FloatField(verbose_name='¿El docente tiene claridad expositiva en el desarrollo de los temas?')),
                ('pregunta_19', models.FloatField(verbose_name='¿El docente desarrolla los temas en una secuencia lógica?')),
            ],
        ),
        migrations.CreateModel(
            name='eval_est',
            fields=[
                ('evaluaciona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='santiguo.evaluaciona')),
                ('pregunta_1', models.FloatField(verbose_name='¿El docente cumple con el horario de clases establecido?')),
                ('pregunta_2', models.FloatField(verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?')),
                ('pregunta_3', models.FloatField(verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?')),
                ('pregunta_4', models.FloatField(verbose_name='¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días?')),
                ('pregunta_5', models.FloatField(verbose_name='¿El docente participa en forma efectiva en tutorías y tribunal de graduación?')),
                ('pregunta_6', models.FloatField(verbose_name='¿El docente cumple en las tareas asignadas por el Director de Carrera?')),
            ],
        ),
        migrations.AddField(
            model_name='evaluaciona',
            name='docentea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santiguo.docentea'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluaciona',
            unique_together={('docentea', 'gestion')},
        ),
    ]
