# Generated by Django 2.0.8 on 2019-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0002_auto_20190307_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentea',
            name='ci',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
