# Generated by Django 2.0.8 on 2019-03-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0003_auto_20190307_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciona',
            name='carrera',
            field=models.CharField(default='No se', max_length=100),
            preserve_default=False,
        ),
    ]
