# Generated by Django 2.0.8 on 2019-03-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0005_auto_20190308_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciona',
            name='pj_llenar',
            field=models.BooleanField(default=False),
        ),
    ]
