# Generated by Django 2.0.8 on 2019-03-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0006_evaluaciona_pj_llenar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciona',
            name='pj_llenar',
        ),
    ]
