# Generated by Django 2.0.8 on 2019-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0008_auto_20190321_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejorasa',
            name='ultimo_generado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
