# Generated by Django 2.0.8 on 2019-05-16 18:18

from django.db import migrations, models
import django.db.models.deletion

def forward(apps, schema_editor):
    evaluaciona = apps.get_model("santiguo", "evaluaciona")
    carrerasa = apps.get_model("santiguo", "carrerasa")
    res = evaluaciona.objects.filter()
    for a in res:
        c = carrerasa.objects.get(nombre=a.carrera)
        a.carrerasa = c
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0010_carrerasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciona',
            name='carrerasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='santiguo.carrerasa'),
            preserve_default=False,
        ),
        migrations.RunPython(forward)
    ]
