# Generated by Django 2.0.8 on 2019-05-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0010_carrerasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciona',
            name='carrerasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='santiguo.carrerasa'),
            preserve_default=False,
        ),
    ]
