# Generated by Django 2.0.8 on 2019-05-20 19:39

from django.db import migrations

def forward(apps, schema_editor):
    evaluaciona = apps.get_model("santiguo", "evaluaciona")
    carrerasa = apps.get_model("santiguo", "carrerasa")
    res = evaluaciona.objects.filter()
    for a in res:
        c = carrerasa.objects.get(nombre=a.carrera)
        a.carrerasa = c
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('santiguo', '0011_evaluaciona_carrerasa'),
    ]

    operations = [
    	migrations.RunPython(forward)
    ]
