# Generated by Django 2.0.5 on 2018-06-04 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='dato no numerico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='[a-zA-Z ]{4,25}')])),
            ],
        ),
    ]
