# Generated by Django 2.0.8 on 2018-11-14 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='ci',
            field=models.CharField(default='203688765', max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El Ci consta de 10 digitos como maximo', regex='^[a-zA-Z0-9-]{6,10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docentes',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El apellido solo debe contener letras y contener mínimo 4 letras ', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóúñ]{2,} )|([a-zA-ZÑÁÉÍÓÚáéíóúñ]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóúñ]{2,} )|([a-zA-ZÑÁÉÍÓÚáéíóúñ]{2,}))+$')]),
        ),
    ]
