# Generated by Django 2.0.5 on 2018-06-06 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20180605_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='[a-zA-ZñÑáéíóúÁÉÍÓÚ ]{4,100}')])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carreras')),
            ],
        ),
        migrations.AlterField(
            model_name='materias',
            name='sigla',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='La sigla contiene tres letras seguidas de un guion y tres números Ej: SIS-130 en mayusculas', regex='[A-Z]{3}-[0-9]{3}')]),
        ),
    ]
