# Generated by Django 2.0.8 on 2018-11-16 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20181114_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='nivel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materias',
            name='sigla',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='La sigla contiene tres letras seguidas de un guion y tres números Ej: SIS-130 en mayusculas', regex='^([A-Z]{3}-[0-9]{3})|[A-Z]{3}[0-9]{3}$')]),
        ),
    ]
