# Generated by Django 2.0.5 on 2018-06-12 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20180606_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras en mayusculas', regex='^[A-ZÑÁÉÍÓÚ ]{4,100}$')]),
        ),
        migrations.AlterField(
            model_name='materias',
            name='nombre',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ ]{4,25}$')]),
        ),
        migrations.AlterField(
            model_name='materias',
            name='sigla',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='La sigla contiene tres letras seguidas de un guion y tres números Ej: SIS-130 en mayusculas', regex='^[A-Z]{3}-[0-9]{3}$')]),
        ),
    ]
