# Generated by Django 2.0.8 on 2019-02-07 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20181116_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='ci',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El Ci consta de 10 digitos como maximo', regex='^[a-zA-Z0-9-]{6,10}$')]),
        ),
    ]
