# Generated by Django 2.0.5 on 2018-06-19 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20180612_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='nombre',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras en mayusculas', regex='^(([A-ZÑÁÉÍÓÚ]{2,} )|([A-ZÑÁÉÍÓÚ]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras en mayusculas', regex='^(([A-ZÑÁÉÍÓÚ]{2,} )|([A-ZÑÁÉÍÓÚ]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='materias',
            name='nombre',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,} )|(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,})))+$')]),
        ),
    ]
