# Generated by Django 2.0.8 on 2021-11-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20190807_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
