# Generated by Django 2.0.8 on 2018-09-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20180619_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='activado_crear',
            field=models.BooleanField(default=False),
        ),
    ]
