# Generated by Django 2.0.8 on 2018-09-21 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_carreras_activado_crear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras en mayusculas', regex='^(([A-ZÑÁÉÍÓÚ]{2,} +)|([A-ZÑÁÉÍÓÚ]{2,}+))$')]),
        ),
    ]
