# Generated by Django 2.0.8 on 2018-09-21 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_auto_20180921_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='apellidos',
            field=models.CharField(default='Castro', max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El apellido solo debe contener letras y contener mínimo 4 letras ', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,} )|([a-zA-ZÑÁÉÍÓÚáéíóú]{2,}))+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carreras',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,} )|([a-zA-ZÑÁÉÍÓÚáéíóú]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,} )|([a-zA-ZÑÁÉÍÓÚáéíóú]{2,}))+$')]),
        ),
    ]
