# Generated by Django 2.0.8 on 2018-09-28 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_auto_20180921_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='nombre',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,} )|([a-zA-ZÑÁÉÍÓÚáéíóú]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='materias',
            name='nombre',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='dato solo alfabetico', message='El nombre solo debe contener letras y contener mínimo 4 letras', regex='^(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,} )|(([a-zA-ZÑÁÉÍÓÚáéíóú]{2,})))+$')]),
        ),
    ]
