# Generated by Django 2.0.8 on 2018-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_auto_20180928_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='activado_crear',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
