# Generated by Django 2.0.8 on 2018-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_auto_20181001_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='activado_crear',
        ),
        migrations.AddField(
            model_name='carreras',
            name='tiempo_activo',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
