# Generated by Django 2.0.8 on 2018-10-01 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_auto_20181001_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='tiempo_activo',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
