# Generated by Django 2.0.5 on 2018-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('usuarios', 'Permiso al modulo de usuarios'), ('academico', 'Permiso al modulo academico'), ('conf_evaluaion', 'Permiso al modulo de inilisacion de evaluacion'), ('evaluacion', 'Permiso al modulo de evaluacion')),
            },
        ),
    ]
