# Generated by Django 2.0.8 on 2018-11-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': (('usuarios', 'Permiso al modulo de usuarios'), ('academico', 'Permiso al modulo academico'), ('conf_evaluaion', 'Permiso al modulo de inilisacion de evaluacion'), ('evaluacion', 'Permiso al modulo de evaluacion'), ('dcarrera', 'Permiso al modulo de director de carrera'))},
        ),
    ]
