# Generated by Django 2.0.8 on 2019-03-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190206_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_docente',
            name='ci',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
