# Generated by Django 2.0.8 on 2019-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejoras',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
