# Generated by Django 2.0.8 on 2019-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0002_plan_mejoras_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_1',
            field=models.TextField(blank=True, null=True, verbose_name='1.- Indicador a la debilidad: ¿El docente cumple con el horario de clases establecido?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_2',
            field=models.TextField(blank=True, null=True, verbose_name='1.- Indicador a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_1',
            field=models.TextField(blank=True, null=True, verbose_name='1.- Meta a la debilidad: ¿El docente cumple con el horario de clases establecido?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_2',
            field=models.TextField(blank=True, null=True, verbose_name='1.- Meta a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_1',
            field=models.TextField(blank=True, null=True, verbose_name='1.- Acción a la debilidad: ¿El docente cumple con el horario de clases establecido?.(AD-EE-ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_2',
            field=models.TextField(blank=True, null=True, verbose_name='2.- Acción a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
    ]
