# Generated by Django 2.0.8 on 2019-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0003_auto_20190315_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_10',
            field=models.TextField(blank=True, null=True, verbose_name='10.- Indicador a la debilidad: ¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_11',
            field=models.TextField(blank=True, null=True, verbose_name='11.- Indicador a la debilidad: ¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_12',
            field=models.TextField(blank=True, null=True, verbose_name='12.- Indicador a la debilidad: ¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_13',
            field=models.TextField(blank=True, null=True, verbose_name='13.- Indicador a la debilidad: ¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_14',
            field=models.TextField(blank=True, null=True, verbose_name='14.- Indicador a la debilidad: ¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_15',
            field=models.TextField(blank=True, null=True, verbose_name='15.- Indicador a la debilidad: ¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_16',
            field=models.TextField(blank=True, null=True, verbose_name='16.- Indicador a la debilidad: ¿El docente domina los temas de la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_17',
            field=models.TextField(blank=True, null=True, verbose_name='17.- Indicador a la debilidad: ¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_18',
            field=models.TextField(blank=True, null=True, verbose_name='18.- Indicador a la debilidad: ¿El docente tiene claridad expositiva en el desarrollo de los temas?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_19',
            field=models.TextField(blank=True, null=True, verbose_name='19.- Indicador a la debilidad: ¿El docente desarrolla los temas en una secuencia lógica?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_3',
            field=models.TextField(blank=True, null=True, verbose_name='3.- Indicador a la debilidad: ¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Indicador a la debilidad: ¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Indicador a la debilidad: ¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Indicador a la debilidad: ¿El docente motiva a los alumnos para la participación activa del mismo en clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_7',
            field=models.TextField(blank=True, null=True, verbose_name='7.- Indicador a la debilidad: ¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_8',
            field=models.TextField(blank=True, null=True, verbose_name='8.- Indicador a la debilidad: ¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicador_9',
            field=models.TextField(blank=True, null=True, verbose_name='9.- Indicador a la debilidad: ¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicadord_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Indicador a la debilidad: ¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días.?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicadord_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Indicador a la debilidad: ¿El docente participa en forma efectiva en tutorías y tribunal de graduación, cuando es designado?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='indicadord_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Indicador a la debilidad: ¿El docente cumple en las tareas asignadas por el Director de Carrera?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_10',
            field=models.TextField(blank=True, null=True, verbose_name='10.- Meta a la debilidad: ¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_11',
            field=models.TextField(blank=True, null=True, verbose_name='11.- Meta a la debilidad: ¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_12',
            field=models.TextField(blank=True, null=True, verbose_name='12.- Meta a la debilidad: ¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_13',
            field=models.TextField(blank=True, null=True, verbose_name='13.- Meta a la debilidad: ¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_14',
            field=models.TextField(blank=True, null=True, verbose_name='14.- Meta a la debilidad: ¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_15',
            field=models.TextField(blank=True, null=True, verbose_name='15.- Meta a la debilidad: ¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_16',
            field=models.TextField(blank=True, null=True, verbose_name='16.- Meta a la debilidad: ¿El docente domina los temas de la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_17',
            field=models.TextField(blank=True, null=True, verbose_name='17.- Meta a la debilidad: ¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_18',
            field=models.TextField(blank=True, null=True, verbose_name='18.- Meta a la debilidad: ¿El docente tiene claridad expositiva en el desarrollo de los temas?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_19',
            field=models.TextField(blank=True, null=True, verbose_name='19.- Meta a la debilidad: ¿El docente desarrolla los temas en una secuencia lógica?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_3',
            field=models.TextField(blank=True, null=True, verbose_name='3.- Meta a la debilidad: ¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Meta a la debilidad: ¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Meta a la debilidad: ¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Meta a la debilidad: ¿El docente motiva a los alumnos para la participación activa del mismo en clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_7',
            field=models.TextField(blank=True, null=True, verbose_name='7.- Meta a la debilidad: ¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_8',
            field=models.TextField(blank=True, null=True, verbose_name='8.- Meta a la debilidad: ¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='meta_9',
            field=models.TextField(blank=True, null=True, verbose_name='9.- Meta a la debilidad: ¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='metad_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Meta a la debilidad: ¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días.?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='metad_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Meta a la debilidad: ¿El docente participa en forma efectiva en tutorías y tribunal de graduación, cuando es designado?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='metad_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Meta a la debilidad: ¿El docente cumple en las tareas asignadas por el Director de Carrera?.(ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='indicador_2',
            field=models.TextField(blank=True, null=True, verbose_name='2.- Indicador a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='meta_2',
            field=models.TextField(blank=True, null=True, verbose_name='2.- Meta a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_10',
            field=models.TextField(blank=True, null=True, verbose_name='10.- Acción a la debilidad: ¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_11',
            field=models.TextField(blank=True, null=True, verbose_name='11.- Acción a la debilidad: ¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_12',
            field=models.TextField(blank=True, null=True, verbose_name='12.- Acción a la debilidad: ¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_13',
            field=models.TextField(blank=True, null=True, verbose_name='13.- Acción a la debilidad: ¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_14',
            field=models.TextField(blank=True, null=True, verbose_name='14.- Acción a la debilidad: ¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_15',
            field=models.TextField(blank=True, null=True, verbose_name='15.- Acción a la debilidad: ¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_16',
            field=models.TextField(blank=True, null=True, verbose_name='16.- Acción a la debilidad: ¿El docente domina los temas de la asignatura?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_17',
            field=models.TextField(blank=True, null=True, verbose_name='17.- Acción a la debilidad: ¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_18',
            field=models.TextField(blank=True, null=True, verbose_name='18.- Acción a la debilidad: ¿El docente tiene claridad expositiva en el desarrollo de los temas?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_19',
            field=models.TextField(blank=True, null=True, verbose_name='19.- Acción a la debilidad: ¿El docente desarrolla los temas en una secuencia lógica?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_3',
            field=models.TextField(blank=True, null=True, verbose_name='3.- Acción a la debilidad: ¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?.(AD-EE-ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Acción a la debilidad: ¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Acción a la debilidad: ¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Acción a la debilidad: ¿El docente motiva a los alumnos para la participación activa del mismo en clases?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_7',
            field=models.TextField(blank=True, null=True, verbose_name='7.- Acción a la debilidad: ¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_8',
            field=models.TextField(blank=True, null=True, verbose_name='8.- Acción a la debilidad: ¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='pregunta_9',
            field=models.TextField(blank=True, null=True, verbose_name='9.- Acción a la debilidad: ¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?.(AD-EE)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='preguntad_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Acción a la debilidad: ¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días.?.(ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='preguntad_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Meta a la debilidad: ¿El docente participa en forma efectiva en tutorías y tribunal de graduación, cuando es designado?.(ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='preguntad_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Meta a la debilidad: ¿El docente cumple en las tareas asignadas por el Director de Carrera?.(ED)'),
        ),
    ]
