# Generated by Django 2.0.8 on 2019-03-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0004_auto_20190318_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_1',
            field=models.TextField(blank=True, null=True, verbose_name='1.- Medio de verificación a la debilidad: Indicador a la debilidad: ¿El docente cumple con el horario de clases establecido?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_10',
            field=models.TextField(blank=True, null=True, verbose_name='10.- Medio de verificación a la debilidad: ¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_11',
            field=models.TextField(blank=True, null=True, verbose_name='11.- Medio de verificación a la debilidad: ¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_12',
            field=models.TextField(blank=True, null=True, verbose_name='12.- Medio de verificación a la debilidad: ¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_13',
            field=models.TextField(blank=True, null=True, verbose_name='13.- Medio de verificación a la debilidad: ¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_14',
            field=models.TextField(blank=True, null=True, verbose_name='14.- Medio de verificación a la debilidad: ¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_15',
            field=models.TextField(blank=True, null=True, verbose_name='15.- Medio de verificación a la debilidad: ¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_16',
            field=models.TextField(blank=True, null=True, verbose_name='16.- Medio de verificación a la debilidad: ¿El docente domina los temas de la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_17',
            field=models.TextField(blank=True, null=True, verbose_name='17.- Medio de verificación a la debilidad: ¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_18',
            field=models.TextField(blank=True, null=True, verbose_name='18.- Medio de verificación a la debilidad: ¿El docente tiene claridad expositiva en el desarrollo de los temas?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_19',
            field=models.TextField(blank=True, null=True, verbose_name='19.- Medio de verificación a la debilidad: ¿El docente desarrolla los temas en una secuencia lógica?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_2',
            field=models.TextField(blank=True, null=True, verbose_name='2.- Medio de verificación a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_3',
            field=models.TextField(blank=True, null=True, verbose_name='3.- Medio de verificación a la debilidad: ¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Medio de verificación a la debilidad: ¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Medio de verificación a la debilidad: ¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Medio de verificación a la debilidad: ¿El docente motiva a los alumnos para la participación activa del mismo en clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_7',
            field=models.TextField(blank=True, null=True, verbose_name='7.- Medio de verificación a la debilidad: ¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_8',
            field=models.TextField(blank=True, null=True, verbose_name='8.- Medio de verificación a la debilidad: ¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_veri_9',
            field=models.TextField(blank=True, null=True, verbose_name='9.- Medio de verificación a la debilidad: ¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_verid_4',
            field=models.TextField(blank=True, null=True, verbose_name='4.- Medio de verificación a la debilidad: ¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días.?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_verid_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Medio de verificación a la debilidad: ¿El docente participa en forma efectiva en tutorías y tribunal de graduación, cuando es designado?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='medio_verid_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.- Medio de verificación a la debilidad: Indicador a la debilidad: ¿El docente cumple en las tareas asignadas por el Director de Carrera?.(ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='preguntad_5',
            field=models.TextField(blank=True, null=True, verbose_name='5.- Acción a la debilidad: ¿El docente participa en forma efectiva en tutorías y tribunal de graduación, cuando es designado?.(ED)'),
        ),
        migrations.AlterField(
            model_name='plan_mejoras',
            name='preguntad_6',
            field=models.TextField(blank=True, null=True, verbose_name='6.-Acción a la debilidad: ¿El docente cumple en las tareas asignadas por el Director de Carrera?.(ED)'),
        ),
    ]
