# Generated by Django 2.0.8 on 2019-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0006_auto_20190318_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_1',
            field=models.DateField(blank=True, null=True, verbose_name='1.- Fecha limite de cumplimiento a la debilidad: Indicador a la debilidad: ¿El docente cumple con el horario de clases establecido?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_10',
            field=models.DateField(blank=True, null=True, verbose_name='10.- Fecha limite de cumplimiento a la debilidad: ¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_11',
            field=models.DateField(blank=True, null=True, verbose_name='11.- Fecha limite de cumplimiento a la debilidad: ¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_12',
            field=models.DateField(blank=True, null=True, verbose_name='12.- Fecha limite de cumplimiento a la debilidad: ¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_13',
            field=models.DateField(blank=True, null=True, verbose_name='13.- Fecha limite de cumplimiento a la debilidad: ¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_14',
            field=models.DateField(blank=True, null=True, verbose_name='14.- Fecha limite de cumplimiento a la debilidad: ¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_15',
            field=models.DateField(blank=True, null=True, verbose_name='15.- Fecha limite de cumplimiento a la debilidad: ¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_16',
            field=models.DateField(blank=True, null=True, verbose_name='16.- Fecha limite de cumplimiento a la debilidad: ¿El docente domina los temas de la asignatura?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_17',
            field=models.DateField(blank=True, null=True, verbose_name='17.- Fecha limite de cumplimiento a la debilidad: ¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_18',
            field=models.DateField(blank=True, null=True, verbose_name='18.- Fecha limite de cumplimiento a la debilidad: ¿El docente tiene claridad expositiva en el desarrollo de los temas?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_19',
            field=models.DateField(blank=True, null=True, verbose_name='19.- Fecha limite de cumplimiento a la debilidad: ¿El docente desarrolla los temas en una secuencia lógica?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_2',
            field=models.DateField(blank=True, null=True, verbose_name='2.- Fecha limite de cumplimiento a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_3',
            field=models.DateField(blank=True, null=True, verbose_name='3.- Fecha limite de cumplimiento a la debilidad: ¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?.(AD-EE-ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_4',
            field=models.DateField(blank=True, null=True, verbose_name='4.- Fecha limite de cumplimiento a la debilidad: ¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_5',
            field=models.DateField(blank=True, null=True, verbose_name='5.- Fecha limite de cumplimiento a la debilidad: ¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_6',
            field=models.DateField(blank=True, null=True, verbose_name='6.- Fecha limite de cumplimiento a la debilidad: ¿El docente motiva a los alumnos para la participación activa del mismo en clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_7',
            field=models.DateField(blank=True, null=True, verbose_name='7.- Fecha limite de cumplimiento a la debilidad: ¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_8',
            field=models.DateField(blank=True, null=True, verbose_name='8.- Fecha limite de cumplimiento a la debilidad: ¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_termino_9',
            field=models.DateField(blank=True, null=True, verbose_name='9.- Fecha limite de cumplimiento a la debilidad: ¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?.(AD-EE)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_terminod_4',
            field=models.DateField(blank=True, null=True, verbose_name='4.- Fecha limite de cumplimiento a la debilidad: ¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días.?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_terminod_5',
            field=models.DateField(blank=True, null=True, verbose_name='5.- Fecha limite de cumplimiento a la debilidad: ¿El docente participa en forma efectiva en tutorías y tribunal de graduación, cuando es designado?.(ED)'),
        ),
        migrations.AddField(
            model_name='plan_mejoras',
            name='fecha_terminod_6',
            field=models.DateField(blank=True, null=True, verbose_name='6.- Fecha limite de cumplimiento a la debilidad: Indicador a la debilidad: ¿El docente cumple en las tareas asignadas por el Director de Carrera?.(ED)'),
        ),
    ]
