# Generated by Django 2.0.8 on 2019-03-19 14:38

import apps.plmejoras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0007_auto_20190319_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_mejoras',
            name='fecha_termino_1',
            field=models.DateField(blank=True, null=True, validators=[apps.plmejoras.models.validate_fecha_minima], verbose_name='1.- Fecha limite de cumplimiento a la debilidad: Indicador a la debilidad: ¿El docente cumple con el horario de clases establecido?.(AD-EE-ED)'),
        ),
    ]
