# Generated by Django 2.0.8 on 2019-03-19 14:51

import apps.plmejoras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0008_auto_20190319_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_mejoras',
            name='fecha_termino_2',
            field=models.DateField(blank=True, null=True, validators=[apps.plmejoras.models.validate_fecha_minima], verbose_name='2.- Fecha limite de cumplimiento a la debilidad: ¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?.(AD-EE-ED)'),
        ),
    ]
