# Generated by Django 2.0.8 on 2019-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmejoras', '0010_auto_20190321_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejoras',
            name='ultimo_generado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
