# Generated by Django 2.0.5 on 2018-06-19 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20180619_1106'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procesoeval', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacion_evaluacion',
            unique_together={('usuario', 'carrera')},
        ),
    ]
