# Generated by Django 2.0.5 on 2018-06-07 19:13

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0003_auto_20180606_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carreras')),
                ('docente', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='carrera', chained_model_field='carrera', on_delete=django.db.models.deletion.CASCADE, to='academico.docentes')),
            ],
        ),
    ]
