# Generated by Django 2.0.8 on 2018-10-01 15:20

import apps.evaluacion.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10)),
                ('veedor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='cuestionario_aevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple con el horario de clases establecido?')),
                ('pregunta_2', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?')),
                ('pregunta_3', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?')),
                ('pregunta_4', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?')),
                ('pregunta_5', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política.?')),
                ('pregunta_6', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente motiva a los alumnos para la participación activa del mismo en clases?')),
                ('pregunta_7', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?')),
                ('pregunta_8', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?')),
                ('pregunta_9', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?')),
                ('pregunta_10', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?')),
                ('pregunta_11', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?')),
                ('pregunta_12', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?')),
                ('pregunta_13', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?')),
                ('pregunta_14', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?')),
                ('pregunta_15', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?')),
                ('pregunta_16', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente domina los temas de la asignatura?')),
                ('pregunta_17', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?')),
                ('pregunta_18', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente tiene claridad expositiva en el desarrollo de los temas?')),
                ('pregunta_19', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente desarrolla los temas en una secuencia lógica?')),
                ('creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuestionario_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple con el horario de clases establecido?')),
                ('pregunta_2', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?')),
                ('pregunta_3', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?')),
                ('pregunta_4', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?')),
                ('pregunta_5', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política.?')),
                ('pregunta_6', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente motiva a los alumnos para la participación activa del mismo en clases?')),
                ('pregunta_7', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?')),
                ('pregunta_8', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?')),
                ('pregunta_9', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?')),
                ('pregunta_10', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?')),
                ('pregunta_11', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?')),
                ('pregunta_12', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?')),
                ('pregunta_13', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?')),
                ('pregunta_14', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?')),
                ('pregunta_15', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?')),
                ('pregunta_16', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente domina los temas de la asignatura?')),
                ('pregunta_17', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?')),
                ('pregunta_18', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente tiene claridad expositiva en el desarrollo de los temas?')),
                ('pregunta_19', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente desarrolla los temas en una secuencia lógica?')),
                ('creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuestionario_dcarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple con el horario de clases establecido?')),
                ('pregunta_2', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?')),
                ('pregunta_3', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?')),
                ('pregunta_4', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días?')),
                ('pregunta_5', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente participa en forma efectiva en tutorías y tribunal de graduación?')),
                ('pregunta_6', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple en las tareas asignadas por el Director de Carrera?')),
                ('creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.PositiveIntegerField(default=2018, validators=[django.core.validators.RegexValidator(code='dato solo numerico', message='El año solo contiene cuatro digitos numericos', regex='^[0-9]{4}$')])),
                ('numero_alumnos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carreras')),
                ('docente', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='carrera', chained_model_field='carrera', on_delete=django.db.models.deletion.CASCADE, to='academico.docentes')),
                ('materia', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='carrera', chained_model_field='carrera', on_delete=django.db.models.deletion.CASCADE, to='academico.materias')),
            ],
        ),
        migrations.CreateModel(
            name='token_aevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ran', models.BigIntegerField(default=apps.evaluacion.models.random_token)),
                ('usado', models.BooleanField(default=False)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='token_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ran', models.BigIntegerField(default=apps.evaluacion.models.random_token)),
                ('usado', models.BooleanField(default=False)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='token_dcarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ran', models.BigIntegerField(default=apps.evaluacion.models.random_token)),
                ('usado', models.BooleanField(default=False)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario_dcarrera',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion'),
        ),
        migrations.AddField(
            model_name='cuestionario_alumno',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion'),
        ),
        migrations.AddField(
            model_name='cuestionario_aevaluacion',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion'),
        ),
        migrations.AddField(
            model_name='comision',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('docente', 'gestion', 'materia')},
        ),
    ]
