# Generated by Django 2.0.5 on 2018-06-07 20:51

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20180606_1734'),
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='materia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='carrera', chained_model_field='carrera', default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.materias'),
            preserve_default=False,
        ),
    ]
