# Generated by Django 2.0.5 on 2018-06-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_evaluacion_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='gestion',
            field=models.PositiveIntegerField(default=2018),
        ),
    ]
