# Generated by Django 2.0.8 on 2018-10-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_auto_20181025_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='token_generate',
            field=models.BooleanField(default=False),
        ),
    ]
