# Generated by Django 2.0.5 on 2018-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20180606_1734'),
        ('evaluacion', '0003_evaluacion_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('docente', 'gestion')},
        ),
    ]
