# Generated by Django 2.0.8 on 2018-10-26 12:39

import apps.evaluacion.setting_dinamic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_auto_20181025_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='periodo',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=apps.evaluacion.setting_dinamic.initial_default_periodo),
        ),
    ]
