# Generated by Django 2.0.5 on 2018-06-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20180606_1734'),
        ('evaluacion', '0004_auto_20180608_1009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('docente', 'gestion', 'materia')},
        ),
    ]
