# Generated by Django 2.0.5 on 2018-06-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_auto_20180612_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ran', models.PositiveIntegerField(default=4095259247)),
                ('usado', models.BooleanField(default=False)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario_alumno',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
