# Generated by Django 2.0.8 on 2019-02-20 20:43

import apps.evaluacion.setting_dinamic
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20190207_0900'),
        ('evaluacion', '0006_auto_20190116_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='comisiong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10)),
                ('gestion', models.PositiveIntegerField(default=apps.evaluacion.setting_dinamic.initial_default_gestion, validators=[django.core.validators.RegexValidator(code='dato solo numerico', message='El año solo contiene cuatro digitos numericos', regex='^[0-9]{4}$')])),
                ('periodo', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=apps.evaluacion.setting_dinamic.initial_default_periodo)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carreras')),
            ],
        ),
    ]
