# Generated by Django 2.0.8 on 2019-02-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0007_comisiong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisiong',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='comisiong',
            unique_together={('ci', 'gestion', 'periodo')},
        ),
    ]
