# Generated by Django 2.0.5 on 2018-06-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluacion', '0007_auto_20180612_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_alumno',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token_alumno',
            name='numero_ran',
            field=models.PositiveIntegerField(default=2342596794),
        ),
    ]
