# Generated by Django 2.0.8 on 2019-02-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20190207_0900'),
        ('evaluacion', '0008_auto_20190220_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comisiong',
            unique_together={('carrera', 'ci', 'gestion', 'periodo')},
        ),
    ]
