# Generated by Django 2.0.5 on 2018-06-14 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluacion', '0009_auto_20180614_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuestionario_dcarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], default=1, verbose_name='¿El docente cumple con el horario de clases establecido?')),
                ('pregunta_2', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], default=1, verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?')),
                ('pregunta_3', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], default=1, verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?')),
                ('pregunta_4', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], default=1, verbose_name='¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días?')),
                ('pregunta_5', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], default=1, verbose_name='¿El docente participa en forma efectiva en tutorías y tribunal de graduación?')),
                ('pregunta_6', models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], default=1, verbose_name='¿El docente cumple en las tareas asignadas por el Director de Carrera?')),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='token_dcarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ran', models.PositiveIntegerField(default=2451787203)),
                ('usado', models.BooleanField(default=False)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='token_alumno',
            name='numero_ran',
            field=models.PositiveIntegerField(default=7153395586),
        ),
    ]
