# Generated by Django 2.0.8 on 2019-02-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_auto_20190220_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='evaluacion',
        ),
        migrations.DeleteModel(
            name='comision',
        ),
    ]
