# Generated by Django 2.0.8 on 2019-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0010_auto_20190226_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario_dcarrera',
            name='ultimo_generado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
