# Generated by Django 2.0.5 on 2018-06-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0010_auto_20180614_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_alumno',
            name='numero_ran',
            field=models.BigIntegerField(default=3842457451),
        ),
        migrations.AlterField(
            model_name='token_dcarrera',
            name='numero_ran',
            field=models.BigIntegerField(default=4264692834),
        ),
    ]
