# Generated by Django 2.0.8 on 2019-09-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20190807_0939'),
        ('evaluacion', '0011_cuestionario_dcarrera_ultimo_generado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('docente', 'gestion', 'materia', 'periodo')},
        ),
    ]
