# Generated by Django 2.0.5 on 2018-06-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0012_auto_20180615_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion'),
        ),
        migrations.AlterField(
            model_name='token_aevaluacion',
            name='numero_ran',
            field=models.BigIntegerField(default=1042207025),
        ),
        migrations.AlterField(
            model_name='token_alumno',
            name='numero_ran',
            field=models.BigIntegerField(default=1484124876),
        ),
        migrations.AlterField(
            model_name='token_dcarrera',
            name='numero_ran',
            field=models.BigIntegerField(default=1873751045),
        ),
    ]
