# Generated by Django 2.0.8 on 2019-11-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20190807_0939'),
        ('evaluacion', '0013_auto_20191128_1635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('docente', 'carrera', 'gestion', 'periodo'), ('docente', 'gestion', 'materia', 'periodo')},
        ),
    ]
