# Generated by Django 2.0.8 on 2018-09-18 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0018_auto_20180917_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='numero_alumnos',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token_aevaluacion',
            name='numero_ran',
            field=models.BigIntegerField(default=3728612697),
        ),
        migrations.AlterField(
            model_name='token_alumno',
            name='numero_ran',
            field=models.BigIntegerField(default=7458380103),
        ),
        migrations.AlterField(
            model_name='token_dcarrera',
            name='numero_ran',
            field=models.BigIntegerField(default=6952208502),
        ),
    ]
