# Generated by Django 2.0.8 on 2018-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0019_auto_20180918_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_1',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple con el horario de clases establecido?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_10',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_11',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_12',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_13',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_14',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_15',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_16',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente domina los temas de la asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_17',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_18',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente tiene claridad expositiva en el desarrollo de los temas?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_19',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente desarrolla los temas en una secuencia lógica?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_2',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_3',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_4',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_5',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política.?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_6',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente motiva a los alumnos para la participación activa del mismo en clases?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_7',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_8',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_aevaluacion',
            name='pregunta_9',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_1',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple con el horario de clases establecido?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_10',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente proporciona la Bibliografía básica contenida en el Plan de asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_11',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente valora los conocimientos previos de los estudiantes, respecto a  las asignaturas precedentes?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_12',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente implementa procedimientos adecuados para la evaluación del aprendizaje?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_13',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente elabora las preguntas de examen en correspondencia con los temas avanzados en la asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_14',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente asigna al estudiante el tiempo suficiente y necesario para la resolución del examen aplicado?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_15',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente informa a los estudiantes sobre los resultados y debilidades identificadas en la evaluación, en un plazo no mayor a los 10 días?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_16',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente domina los temas de la asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_17',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente aclara las preguntas efectuadas por los alumnos sobre los temas avanzados?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_18',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente tiene claridad expositiva en el desarrollo de los temas?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_19',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente desarrolla los temas en una secuencia lógica?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_2',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_3',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_4',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente promueve el análisis crítico, la creatividad y el aprendizaje independiente en los estudiantes?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_5',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente se relaciona con los estudiantes sin discriminación de raza, género, clase social, posición económica, credo religioso o ideología-política.?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_6',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente motiva a los alumnos para la participación activa del mismo en clases?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_7',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presta atención individual o colectiva a los alumnos que solicitan consulta fuera de horarios de clases?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_8',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente utiliza medios educativos de apoyo al aprendizaje, tales como Pizarra, retroproyector  u otros?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_alumno',
            name='pregunta_9',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente facilita texto guía, apuntes, guías de ejercicios prácticos u otros materiales preparados por él?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_dcarrera',
            name='pregunta_1',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple con el horario de clases establecido?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_dcarrera',
            name='pregunta_2',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente presenta el Plan de asignatura a los estudiantes al inicio de la actividad académica?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_dcarrera',
            name='pregunta_3',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente concluye los contenidos temáticos y/o actividades propuestos en el Plan de asignatura?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_dcarrera',
            name='pregunta_4',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente publica y entrega las calificaciones, en un plazo no mayor a los 10 días?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_dcarrera',
            name='pregunta_5',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente participa en forma efectiva en tutorías y tribunal de graduación?'),
        ),
        migrations.AlterField(
            model_name='cuestionario_dcarrera',
            name='pregunta_6',
            field=models.PositiveIntegerField(choices=[(1, 'Nunca'), (2, 'Casi Nunca'), (3, 'A Veces'), (4, 'Casi Siempre'), (5, 'Siempre')], verbose_name='¿El docente cumple en las tareas asignadas por el Director de Carrera?'),
        ),
        migrations.AlterField(
            model_name='token_aevaluacion',
            name='numero_ran',
            field=models.BigIntegerField(default=9286647025),
        ),
        migrations.AlterField(
            model_name='token_alumno',
            name='numero_ran',
            field=models.BigIntegerField(default=1029059877),
        ),
        migrations.AlterField(
            model_name='token_dcarrera',
            name='numero_ran',
            field=models.BigIntegerField(default=1975197407),
        ),
    ]
