# Generated by Django 2.0.8 on 2018-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0025_auto_20180928_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_aevaluacion',
            name='numero_ran',
            field=models.BigIntegerField(default=4928820701),
        ),
        migrations.AlterField(
            model_name='token_alumno',
            name='numero_ran',
            field=models.BigIntegerField(default=7524401394),
        ),
        migrations.AlterField(
            model_name='token_dcarrera',
            name='numero_ran',
            field=models.BigIntegerField(default=2281285960),
        ),
    ]
